SELECT 'af' as code, 'Afrikaans' as name UNION ALL
SELECT 'ak', 'Akan' UNION ALL
SELECT 'am', 'Amharic' UNION ALL
SELECT 'ar', 'Arabic' UNION ALL
SELECT 'bg', 'Bulgarian' UNION ALL
SELECT 'bn', 'Bengali' UNION ALL
SELECT 'bs', 'Bosnian' UNION ALL
SELECT 'ca', 'Catalan' UNION ALL
SELECT 'cn', 'Chinese' UNION ALL
SELECT 'cs', 'Czech' UNION ALL
SELECT 'cy', 'Welsh' UNION ALL
SELECT 'da', 'Danish' UNION ALL
SELECT 'de', 'German' UNION ALL
SELECT 'dz', 'Dzongkha' UNION ALL
SELECT 'el', 'Greek' UNION ALL
SELECT 'en', 'English' UNION ALL
SELECT 'es', 'Spanish' UNION ALL
SELECT 'et', 'Estonian' UNION ALL
SELECT 'eu', 'Basque' UNION ALL
SELECT 'fa', 'Persian' UNION ALL
SELECT 'fi', 'Finnish' UNION ALL
SELECT 'fr', 'French' UNION ALL
SELECT 'ga', 'Irish' UNION ALL
SELECT 'he', 'Hebrew' UNION ALL
SELECT 'hi', 'Hindi' UNION ALL
SELECT 'hr', 'Croatian' UNION ALL
SELECT 'hu', 'Hungarian' UNION ALL
SELECT 'hy', 'Armenian' UNION ALL
SELECT 'id', 'Indonesian' UNION ALL
SELECT 'ig', 'Igbo' UNION ALL
SELECT 'is', 'Icelandic' UNION ALL
SELECT 'it', 'Italian' UNION ALL
SELECT 'ja', 'Japanese' UNION ALL
SELECT 'ka', 'Georgian' UNION ALL
SELECT 'kk', 'Kazakh' UNION ALL
SELECT 'kn', 'Kannada' UNION ALL
SELECT 'ko', 'Korean' UNION ALL
SELECT 'ku', 'Kurdish' UNION ALL
SELECT 'lg', 'Luganda' UNION ALL
SELECT 'lv', 'Latvian' UNION ALL
SELECT 'mk', 'Macedonian' UNION ALL
SELECT 'ml', 'Malayalam' UNION ALL
SELECT 'mr', 'Marathi' UNION ALL
SELECT 'ms', 'Malay' UNION ALL
SELECT 'ne', 'Nepali' UNION ALL
SELECT 'nl', 'Dutch' UNION ALL
SELECT 'no', 'Norwegian' UNION ALL
SELECT 'pa', 'Punjabi' UNION ALL
SELECT 'pl', 'Polish' UNION ALL
SELECT 'ps', 'Pashto' UNION ALL
SELECT 'pt', 'Portuguese' UNION ALL
SELECT 'ro', 'Romanian' UNION ALL
SELECT 'ru', 'Russian' UNION ALL
SELECT 'sl', 'Slovenian' UNION ALL
SELECT 'sq', 'Albanian' UNION ALL
SELECT 'sr', 'Serbian' UNION ALL
SELECT 'sv', 'Swedish' UNION ALL
SELECT 'sw', 'Swahili' UNION ALL
SELECT 'th', 'Thai' UNION ALL
SELECT 'tl', 'Tagalog' UNION ALL
SELECT 'tr', 'Turkish' UNION ALL
SELECT 'uk', 'Ukrainian' UNION ALL
SELECT 'ur', 'Urdu' UNION ALL
SELECT 'xh', 'Xhosa' UNION ALL
SELECT 'xx', 'No Language' UNION ALL
SELECT 'yi', 'Yiddish' UNION ALL
SELECT 'zh', 'Chinese'