SELECT 'Action' AS genre, SUM(genre_action) AS count, AVG(weighted_score) AS weighted_score FROM {{ ref('fa_total_cinema_box_office_join') }} where genre_action = 1 UNION ALL
SELECT 'Adventure', SUM(genre_adventure) , AVG(weighted_score) AS weighted_score FROM {{ ref('fa_total_cinema_box_office_join') }} where genre_adventure = 1 UNION ALL
SELECT 'Animation', SUM(genre_animation) , AVG(weighted_score) AS weighted_score FROM {{ ref('fa_total_cinema_box_office_join') }} where genre_animation = 1 UNION ALL
SELECT 'Comedy', SUM(genre_comedy) , AVG(weighted_score) AS weighted_score FROM {{ ref('fa_total_cinema_box_office_join') }} where genre_comedy = 1 UNION ALL
SELECT 'Crime', SUM(genre_crime) , AVG(weighted_score) AS weighted_score FROM {{ ref('fa_total_cinema_box_office_join') }} where genre_crime = 1 UNION ALL
SELECT 'Documentary', SUM(genre_documentary) , AVG(weighted_score) AS weighted_score FROM {{ ref('fa_total_cinema_box_office_join') }} where genre_documentary = 1 UNION ALL
SELECT 'Drama', SUM(genre_drama) , AVG(weighted_score) AS weighted_score FROM {{ ref('fa_total_cinema_box_office_join') }} where genre_drama = 1 UNION ALL
SELECT 'Family', SUM(genre_family) , AVG(weighted_score) AS weighted_score FROM {{ ref('fa_total_cinema_box_office_join') }} where genre_family = 1 UNION ALL
SELECT 'Fantasy', SUM(genre_fantasy) , AVG(weighted_score) AS weighted_score FROM {{ ref('fa_total_cinema_box_office_join') }} where genre_fantasy = 1 UNION ALL
SELECT 'History', SUM(genre_history) , AVG(weighted_score) AS weighted_score FROM {{ ref('fa_total_cinema_box_office_join') }} where genre_history = 1 UNION ALL
SELECT 'Horror', SUM(genre_horror) , AVG(weighted_score) AS weighted_score FROM {{ ref('fa_total_cinema_box_office_join') }} where genre_horror = 1 UNION ALL
SELECT 'Music', SUM(genre_music) , AVG(weighted_score) AS weighted_score FROM {{ ref('fa_total_cinema_box_office_join') }} where genre_music = 1 UNION ALL
SELECT 'Mystery', SUM(genre_mystery) , AVG(weighted_score) AS weighted_score FROM {{ ref('fa_total_cinema_box_office_join') }} where genre_mystery = 1 UNION ALL
SELECT 'Romance', SUM(genre_romance) , AVG(weighted_score) AS weighted_score FROM {{ ref('fa_total_cinema_box_office_join') }} where genre_romance = 1 UNION ALL
SELECT 'Sci-Fi', SUM(genre_scifi) , AVG(weighted_score) AS weighted_score FROM {{ ref('fa_total_cinema_box_office_join') }} where genre_scifi = 1 UNION ALL
SELECT 'TV Movie', SUM(genre_tv_movie) , AVG(weighted_score) AS weighted_score FROM {{ ref('fa_total_cinema_box_office_join') }} where genre_tv_movie = 1 UNION ALL
SELECT 'Thriller', SUM(genre_thriller) , AVG(weighted_score) AS weighted_score FROM {{ ref('fa_total_cinema_box_office_join') }} where genre_thriller = 1 UNION ALL
SELECT 'War', SUM(genre_war) , AVG(weighted_score) AS weighted_score FROM {{ ref('fa_total_cinema_box_office_join') }} where genre_war = 1 UNION ALL
SELECT 'Western', SUM(genre_western) , AVG(weighted_score) AS weighted_score FROM {{ ref('fa_total_cinema_box_office_join') }} where genre_western = 1 